// Package shim provides functionality for generating the helm shim script
// and shell initialization code.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateShimScript creates the helm shim script at $HELMENV_ROOT/shims/helm.
// The shim resolves the correct helm version and executes it.
func GenerateShimScript(helmenvRoot string) error {
	shimsDir := filepath.Join(helmenvRoot, "shims")
	if err := os.MkdirAll(shimsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create shims directory: %w", err)
	}

	shimPath := filepath.Join(shimsDir, "helm")
	shimContent := fmt.Sprintf(`#!/bin/sh
# This shim is generated by helm-env. Do not edit manually.
set -e

HELMENV_ROOT="%s"

# Resolve version: HELMENV_VERSION > .helm-version (walk up) > $HELMENV_ROOT/version
resolve_version() {
    # 1. Check HELMENV_VERSION env var (shell version)
    if [ -n "$HELMENV_VERSION" ]; then
        echo "$HELMENV_VERSION"
        return
    fi

    # 2. Walk up directories looking for .helm-version (local version)
    local dir="$PWD"
    while true; do
        if [ -f "$dir/.helm-version" ]; then
            cat "$dir/.helm-version"
            return
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            break
        fi
        dir="$parent"
    done

    # 3. Check global version
    if [ -f "$HELMENV_ROOT/version" ]; then
        cat "$HELMENV_ROOT/version"
        return
    fi

    echo "helm-env: no helm version configured" >&2
    echo "Set a version using 'helm-env shell', 'helm-env local', or 'helm-env global'" >&2
    exit 1
}

VERSION="$(resolve_version)"
BINARY="$HELMENV_ROOT/versions/$VERSION/helm"

if [ ! -x "$BINARY" ]; then
    echo "helm-env: version $VERSION is not installed" >&2
    echo "Install it with: helm-env install $VERSION" >&2
    exit 1
fi

exec "$BINARY" "$@"
`, helmenvRoot)

	if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
		return fmt.Errorf("failed to write shim script: %w", err)
	}

	return nil
}

// GenerateShellInit returns the shell initialization code that should be
// eval'd in the user's shell (e.g., eval "$(helm-env init)").
// It creates a shell function that intercepts the 'shell' subcommand to
// set/unset HELMENV_VERSION in the current shell, and prepends the shims
// directory to PATH.
func GenerateShellInit(helmenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

helm-env() {
  if [ "$1" = "shell" ]; then
    if [ -n "$2" ]; then
      # Validate via the real binary first
      command helm-env shell "$2" || return $?
      export HELMENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command helm-env shell
    fi
  else
    command helm-env "$@"
  fi
}
`, helmenvRoot)
}
