// Package shim provides functionality for generating the helm shim script
// and shell initialization code.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateShimScript creates the helm shim script at $HELMENV_ROOT/shims/helm.
// The shim resolves the correct helm version and executes it.
func GenerateShimScript(helmenvRoot string) error {
	shimsDir := filepath.Join(helmenvRoot, "shims")
	if err := os.MkdirAll(shimsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create shims directory: %w", err)
	}

	shimPath := filepath.Join(shimsDir, "helm")
	shimContent := fmt.Sprintf(`#!/bin/sh
# This shim is generated by helm-env. Do not edit manually.
set -e

HELMENV_ROOT="%s"

# resolve_raw returns the version/constraint string from the first configured
# source: HELMENV_VERSION > .helm-version (walk up) > $HELMENV_ROOT/version.
# It does NOT consult installed versions.
resolve_raw() {
    if [ -n "$HELMENV_VERSION" ]; then
        printf '%%s\n' "$HELMENV_VERSION"
        return 0
    fi

    dir="$PWD"
    while true; do
        if [ -f "$dir/.helm-version" ]; then
            cat "$dir/.helm-version"
            return 0
        fi
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            break
        fi
        dir="$parent"
    done

    if [ -f "$HELMENV_ROOT/version" ]; then
        cat "$HELMENV_ROOT/version"
        return 0
    fi

    return 1
}

# is_exact_semver returns 0 (success) if $1 is a plain MAJOR.MINOR.PATCH[-pre].
is_exact_semver() {
    case "$1" in
        *,*|*~*|*^*|*\<*|*\>*|*=*) return 1 ;;
        latest|latest-stable|latest-installed|stable) return 1 ;;
    esac
    # Strip optional leading v.
    v="${1#v}"
    # Strip optional -prerelease suffix.
    core="${v%%-*}"
    IFS=.
    set -- $core
    unset IFS
    [ $# -eq 3 ] || return 1
    for seg in "$1" "$2" "$3"; do
        case "$seg" in
            ''|*[!0-9]*) return 1 ;;
        esac
    done
    return 0
}

RAW_VERSION="$(resolve_raw)" || {
    echo "helm-env: no helm version configured" >&2
    echo "Set a version using 'helm-env shell', 'helm-env local', or 'helm-env global'" >&2
    exit 1
}
RAW_VERSION="$(printf '%%s' "$RAW_VERSION" | tr -d '[:space:]')"

# Fast path: raw value is an exact semver AND is installed.
if is_exact_semver "$RAW_VERSION" && [ -x "$HELMENV_ROOT/versions/$RAW_VERSION/helm" ]; then
    VERSION="$RAW_VERSION"
else
    # Slow path: shell out to helm-env to resolve constraint / alias.
    if VERSION="$(command helm-env resolve --concrete 2>/dev/null)"; then
        :
    else
        VERSION=""
    fi
fi

if [ -z "$VERSION" ] || [ ! -x "$HELMENV_ROOT/versions/$VERSION/helm" ]; then
    case "${HELMENV_AUTO_INSTALL:-}" in
        1|true|TRUE|True|yes|YES|Yes|on|ON|On)
            # Auto-install: ask helm-env to install the resolved version.
            TARGET="${VERSION:-$RAW_VERSION}"
            if command helm-env install --silent "$TARGET" >&2; then
                # Re-resolve in case TARGET was a constraint.
                if NEW_VERSION="$(command helm-env resolve --concrete 2>/dev/null)"; then
                    VERSION="$NEW_VERSION"
                fi
            fi
            ;;
    esac
fi

BINARY="$HELMENV_ROOT/versions/$VERSION/helm"
if [ -z "$VERSION" ] || [ ! -x "$BINARY" ]; then
    DISPLAY="${VERSION:-$RAW_VERSION}"
    echo "helm-env: version $DISPLAY is not installed" >&2
    echo "Install it with: helm-env install $DISPLAY" >&2
    echo "Hint: set HELMENV_AUTO_INSTALL=1 to install missing versions automatically." >&2
    exit 1
fi

exec "$BINARY" "$@"
`, helmenvRoot)

	if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
		return fmt.Errorf("failed to write shim script: %w", err)
	}

	return nil
}

// GenerateShellInit returns the shell initialization code that should be
// eval'd in the user's shell (e.g., eval "$(helm-env init)").
// It creates a shell function that intercepts the 'shell' subcommand to
// set/unset HELMENV_VERSION in the current shell, and prepends the shims
// directory to PATH.
func GenerateShellInit(helmenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

helm-env() {
  if [ "$1" = "shell" ]; then
    if [ -n "$2" ]; then
      # Validate via the real binary first
      command helm-env shell "$2" || return $?
      export HELMENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command helm-env shell
    fi
  else
    command helm-env "$@"
  fi
}
`, helmenvRoot)
}
