// Package main is the entry point for the helm-env CLI tool.
package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/user/helm-env/internal/commands"
)

// Version is set at build time via ldflags:
//
//	go build -ldflags "-X main.Version=0.1.0"
var Version = "dev"

func main() {
	// Inject version into commands package
	commands.Version = Version

	args := os.Args[1:]

	if len(args) == 0 {
		commands.Help()
		os.Exit(0)
	}

	var err error

	switch args[0] {
	case "help", "--help", "-h":
		commands.Help()

	case "version", "--version", "-v":
		commands.PrintVersion()

	case "init":
		err = commands.Init()

	case "list":
		err = commands.List()

	case "list-remote":
		includePrerelease := false
		for _, arg := range args[1:] {
			switch arg {
			case "-h", "--help":
				commands.ListRemoteHelp()
				os.Exit(0)
			case "--prerelease":
				includePrerelease = true
			}
		}
		err = commands.ListRemote(includePrerelease)

	case "latest":
		includePrerelease := false
		for _, arg := range args[1:] {
			switch arg {
			case "-h", "--help":
				commands.LatestHelp()
				os.Exit(0)
			case "--prerelease":
				includePrerelease = true
			}
		}
		err = commands.Latest(includePrerelease)

	case "install":
		version := ""
		silent := false
		for _, arg := range args[1:] {
			if arg == "-s" || arg == "--silent" {
				silent = true
			} else if arg == "-h" || arg == "--help" {
				commands.InstallHelp()
				os.Exit(0)
			} else if version == "" && !strings.HasPrefix(arg, "-") {
				version = arg
			}
		}
		err = commands.Install(version, silent)

	case "uninstall":
		if wantsHelp(args[1:]) {
			commands.UninstallHelp()
			os.Exit(0)
		}
		version := ""
		if len(args) > 1 {
			version = args[1]
		}
		err = commands.Uninstall(version)

	case "shell":
		if wantsHelp(args[1:]) {
			commands.ShellHelp()
			os.Exit(0)
		}
		version := ""
		if len(args) > 1 {
			version = args[1]
		}
		err = commands.Shell(version)

	case "local":
		if wantsHelp(args[1:]) {
			commands.LocalHelp()
			os.Exit(0)
		}
		version := ""
		if len(args) > 1 {
			version = args[1]
		}
		err = commands.Local(version)

	case "global":
		if wantsHelp(args[1:]) {
			commands.GlobalHelp()
			os.Exit(0)
		}
		version := ""
		if len(args) > 1 {
			version = args[1]
		}
		err = commands.Global(version)

	case "which":
		explain := false
		for _, arg := range args[1:] {
			switch arg {
			case "--explain":
				explain = true
			case "-h", "--help":
				commands.WhichHelp()
				os.Exit(0)
			}
		}
		err = commands.Which(explain)

	case "upgrade":
		// -h must never fall through to a real upgrade.
		if wantsHelp(args[1:]) {
			commands.UpgradeHelp()
			os.Exit(0)
		}
		if len(args) > 1 {
			err = fmt.Errorf("upgrade takes no arguments (got %q); see 'helm-env upgrade --help'", args[1])
		} else {
			err = commands.Upgrade()
		}

	case "completion", "autocompletion":
		// `autocompletion` is a deprecated, hidden alias with the same
		// arguments as `completion`.
		if args[0] == "autocompletion" {
			fmt.Fprintln(os.Stderr, commands.AutocompletionDeprecation)
		}
		shell, help, perr := commands.ParseCompletionArgs(args[1:])
		if help {
			commands.CompletionHelp()
			os.Exit(0)
		}
		if perr != nil {
			err = perr
		} else {
			err = commands.Completion(shell)
		}

	case "status":
		err = commands.Status()

	case "resolve":
		spec := ""
		install := false
		silent := false
		for _, arg := range args[1:] {
			switch {
			case arg == "-h" || arg == "--help":
				commands.ResolveHelp()
				os.Exit(0)
			case arg == "--concrete":
				// Legacy no-op: output is always concrete. Kept because
				// shims generated by older releases still pass it.
			case arg == "--install":
				install = true
			case arg == "-s" || arg == "--silent":
				silent = true
			case strings.HasPrefix(arg, "-"):
				err = fmt.Errorf("unknown flag %q for resolve", arg)
			case spec == "":
				spec = arg
			default:
				err = fmt.Errorf("resolve takes at most one version spec (got %q and %q)", spec, arg)
			}
			if err != nil {
				break
			}
		}
		if err == nil {
			err = commands.Resolve(spec, install, silent)
		}

	case "prune":
		keep := 0
		olderThan := ""
		dryRun := false
		yes := false
		for i := 1; i < len(args); i++ {
			arg := args[i]
			switch {
			case arg == "--dry-run":
				dryRun = true
			case arg == "--yes":
				yes = true
			case arg == "--keep-last" || arg == "--keep":
				// --keep is a deprecated alias for --keep-last.
				if i+1 >= len(args) {
					err = fmt.Errorf("%s requires a value", arg)
				} else {
					i++
					if _, perr := fmt.Sscanf(args[i], "%d", &keep); perr != nil {
						err = fmt.Errorf("invalid %s value %q: %w", arg, args[i], perr)
					}
				}
			case strings.HasPrefix(arg, "--keep-last=") || strings.HasPrefix(arg, "--keep="):
				name, val, _ := strings.Cut(arg, "=")
				if _, perr := fmt.Sscanf(val, "%d", &keep); perr != nil {
					err = fmt.Errorf("invalid %s value: %w", name, perr)
				}
			case arg == "--older-than":
				if i+1 >= len(args) {
					err = fmt.Errorf("--older-than requires a value")
				} else {
					i++
					olderThan = args[i]
				}
			case strings.HasPrefix(arg, "--older-than="):
				olderThan = strings.TrimPrefix(arg, "--older-than=")
			case arg == "-h" || arg == "--help":
				commands.PruneHelp()
				os.Exit(0)
			default:
				err = fmt.Errorf("unknown flag %q for prune", arg)
			}
			if err != nil {
				break
			}
		}
		if err == nil {
			err = commands.Prune(keep, olderThan, dryRun, yes)
		}

	case "doctor":
		fix := false
		for _, arg := range args[1:] {
			switch arg {
			case "-h", "--help":
				commands.DoctorHelp()
				os.Exit(0)
			case "--fix":
				fix = true
			default:
				if err == nil {
					err = fmt.Errorf("unknown flag %q for doctor", arg)
				}
			}
		}
		if err == nil {
			err = commands.Doctor(fix)
		}

	case "exec":
		version := ""
		execArgs := []string{}
		auto := commands.AutoFromEnv()
		foundVersion := false
		for i := 1; i < len(args); i++ {
			arg := args[i]
			switch arg {
			case "-h", "--help":
				// Only before <spec>; afterwards everything belongs to helm.
				commands.ExecHelp()
				os.Exit(0)
			case "--auto":
				auto = commands.AutoForce
			case "--no-auto":
				auto = commands.AutoDisabled
			default:
				if !foundVersion && !strings.HasPrefix(arg, "-") {
					version = arg
					foundVersion = true
					if i+1 < len(args) {
						execArgs = args[i+1:]
					}
					i = len(args)
				}
			}
		}
		err = commands.ExecWithOptions(version, execArgs, auto)

	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\n\n", args[0])
		commands.Help()
		os.Exit(1)
	}

	if err != nil {
		// `exec`: pass the child's exit code through without printing
		// "exit status N" (the child already reported its own error).
		if code, ok := childExitCode(err); ok {
			os.Exit(code)
		}
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// wantsHelp reports whether args contain -h or --help.
func wantsHelp(args []string) bool {
	for _, arg := range args {
		if arg == "-h" || arg == "--help" {
			return true
		}
	}
	return false
}

// childExitCode returns the exit code of a child process that ran and
// exited non-zero. A child killed by a signal has no exit code and maps to 1.
func childExitCode(err error) (int, bool) {
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		return 0, false
	}
	if code := exitErr.ExitCode(); code > 0 {
		return code, true
	}
	return 1, true
}
